/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.gui;

import easy.classes.Product;
import easy.controller.dao.ProductDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yasas Sri
 */
public class ProductSearchWindow extends javax.swing.JFrame {

    public ProductSearchWindow() {
        initComponents();
        this.updateLables();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotProfits = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbltotItems = new javax.swing.JLabel();
        lblAvailableItems = new javax.swing.JLabel();
        lblSoldItems = new javax.swing.JLabel();
        lblTotInves = new javax.swing.JLabel();
        lblTotSales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\YasasSri\\Documents\\NetBeansProjects\\easyinventary_edited\\imgs\\Search-good-icon.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Source Code Pro Light", 0, 36)); // NOI18N
        jLabel2.setText("Easy Inventory");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 40));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("Type Product Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 80, 30));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 270, 30));

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tag Number", "Item Name", "Item Brand", "Cost Price", "Selling Price", "Profit", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 570, 240));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 120, 50));

        btnSell.setIcon(new javax.swing.ImageIcon("C:\\Users\\YasasSri\\Documents\\NetBeansProjects\\easyinventary_edited\\imgs\\shop-cart-add-icon.png")); // NOI18N
        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        jPanel1.add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 150, 70));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 120, 50));

        btnAdd.setText("Add New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 120, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total Profits");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total Sales");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Total Investment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Sold Items");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Available Items");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        lblTotProfits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblTotProfits, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Total Items");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        lbltotItems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lbltotItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 110, 30));

        lblAvailableItems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblAvailableItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 110, 30));

        lblSoldItems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblSoldItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, 110, 30));

        lblTotInves.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblTotInves, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 110, 30));

        lblTotSales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblTotSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchtext = txtSearch.getText();

        try {
            ProductDAO productdao = new ProductDAO();
            ArrayList<Product> items = new ArrayList<>();
            if (searchtext != null && searchtext.trim().length() > 0) {
                items = productdao.searchProduct(searchtext);
            } else {
                items = productdao.getAllProduct();
            }
            // Using table Model
            ProductTableModel model = new ProductTableModel(items);
            tblList.setModel(model);

            this.updateLables();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        try {
            ProductDAO productdao = new ProductDAO();
            int row = tblList.getSelectedRow();

            if (row < 0) {
                JOptionPane.showMessageDialog(null, "Error", "You must select a Product.", JOptionPane.ERROR_MESSAGE);

                return;
            }
            int response = JOptionPane.showConfirmDialog(null, "Sell this products?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response != JOptionPane.YES_OPTION) {
                return;
            }

            Product tmpProduct = (Product) tblList.getValueAt(row, ProductTableModel.OBJECT_COL);

            try {
                productdao.soldItem(tmpProduct.getId());
                updateLables();
            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            ProductDAO productdao = new ProductDAO();
            int row = tblList.getSelectedRow();

            if (row < 0) {
                JOptionPane.showMessageDialog(null, "Error", "You must select a Product.", JOptionPane.ERROR_MESSAGE);

                return;
            }
            int response = JOptionPane.showConfirmDialog(null, "Delete this product?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response != JOptionPane.YES_OPTION) {
                return;
            }

            Product tmpProduct = (Product) tblList.getValueAt(row, ProductTableModel.OBJECT_COL);

            try {
                productdao.deleteItem(tmpProduct.getId());
                updateLables();
            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            ProductDAO productdao = new ProductDAO();
            int row = tblList.getSelectedRow();

            if (row < 0) {
                JOptionPane.showMessageDialog(null, "You must select a Product.", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            Product tmpProduct = (Product) tblList.getValueAt(row, ProductTableModel.OBJECT_COL);

            //System.out.println(tmpProduct);
            AddNewProductItem dialog = new AddNewProductItem(productdao, ProductSearchWindow.this, tmpProduct, true);

            dialog.setVisible(true);

            ProductDAO productdao1 = new ProductDAO();
            ArrayList<Product> items = new ArrayList<>();
            if (txtSearch.getText() != null && txtSearch.getText().trim().length() > 0) {
                items = productdao1.searchProduct(txtSearch.getText());
            } else {
                items = productdao1.getAllProduct();
            }
            // Using table Model
            ProductTableModel model = new ProductTableModel(items);
            tblList.setModel(model);

            this.updateLables();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            ProductDAO productdao = new ProductDAO();
            AddNewProductItem dialog = new AddNewProductItem(productdao, ProductSearchWindow.this);
            dialog.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_btnAddActionPerformed

    void updateLables() {
        try {
            ProductDAO productdao = new ProductDAO();

            String totalItems = productdao.getTotalItems();
            lbltotItems.setText(totalItems);

            String availableItems = productdao.getAvaiItems();
            lblAvailableItems.setText(availableItems);

            String soldItems = productdao.getSoldItems();
            lblSoldItems.setText(soldItems);

            String totalInvestment = productdao.getTotalInvest();
            lblTotInves.setText(totalInvestment);

            String totalSales = productdao.getTotalSell();
            lblTotSales.setText(totalSales);

            String totalProfits = productdao.getProfit();
            lblTotProfits.setText(totalProfits);

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            // select Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            // start application

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailableItems;
    private javax.swing.JLabel lblSoldItems;
    private javax.swing.JLabel lblTotInves;
    private javax.swing.JLabel lblTotProfits;
    private javax.swing.JLabel lblTotSales;
    private javax.swing.JLabel lbltotItems;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
